# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dateJoined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profilePic',
        ),
    ]
